name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bear_build:latest
    - name: Create container
      run: docker create --name bear_build_extract bear_build:latest
    - name: Copy artifacts
      run: docker cp bear_build_extract:/home/build/packages .
    - name: Remove container
      run: docker rm bear_build_extract
    - uses: actions/upload-artifact@v2
      with:
        name: bear-SNAPSHOT
        path: packages/*
